python train.py \
--dataset_path ~/Research/Cell_recognition/dataset/dataset/ \
--ckpt_path ./checkpoints/tryout \
--results_path ./results/tryout \
--n_cl 2 \
--network build \
--epochs 40 \
--batch_size 16 \
--shape 224 \